# The address to listen on. ServerName@address:port
ListenAt: YavarSystem@127.0.0.1:12314
# A list of servers that events will be passed on to. ServerName@address:port
SendTo:
    - CoreSystem@127.0.0.1:12300
#The server's assigned ID. Should match the last 1 or 2 digits of the ListenAt port
ServerID: 14
#List as "true" or "false", indicates whether this is a hub or just a spoke
IsHub: false