System: Trinitos_Alpha
defaultBedspawnServer: Trinitos_Alpha
defaultBedspawnWorld: Trinitos_Alpha
defaultBedspawnX: -2475
defaultBedspawnY: 50
defaultBedspawnZ: -2475

Host: play.starquestminecraft.com
Database: minecraft
User: minecraft
Pass: gghax0rs

Locale: en
PilotTool: 347

Loyavas:
    Xcoord: 1500
    Ycoord: 200
    Zcoord: -2598
Cetallion:
    Xcoord: -2500
    Ycoord: 200
    Zcoord: 0
Rakuria:
    Xcoord: -574
    Ycoord: 200
    Zcoord: -1386
Grun:
    Xcoord: 0
    Ycoord: 100
    Zcoord: 1000
Trinitos_Gamma:
    Xcoord: -750
    Ycoord: 100
    Zcoord: 3250
    XcoordTarget: 100
    YcoordTarget: 100
    ZcoordTarget: -4249
    orientation: 0
Trinitos_Beta:
    Xcoord: 4000
    Ycoord: 100
    Zcoord: 0
    XcoordTarget: -4700
    YcoordTarget: 100
    ZcoordTarget: 0
    orientation: 1